language: java

# explicit distribution specification
# to use xvfb as a service
dist: xenial

jdk: openjdk8

services:
   - docker
   - xvfb

addons:
  sonarcloud:
    organization: "lorenzobettini-github"

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - git fetch --unshallow
   - mvn -f com.examples.school/pom.xml -Pjacoco clean verify sonar:sonar
